### ISSUE TITLE
timesteps during the training

### ISSUE THREAD

**Issue by ssssholmes** [CompVis/depth-fm#4]
Hi, thanks for great work. I found the provided checkpoint has a fixed tilmestep 400. which is not explained in the paper. It is really appreciated to help me make it more clear for the following questions:

1. do you use a fixed tilmestep for the input of unet during the training
2. during the training, do you directly add gaussian noise to the rgb latent, without using the q_sample function

Thanks very much.

**Comment by mgui7** [comment]
Hi ssssholmes, timestep 400 is a setting here for the noise augmentation, which noises the starting image at $x_0$ a bit to enhance overall model performance. To answer you questions specifically:

- Like regular flow matching and diffusion model training, we randomly sample $t$ during training
- We always noise the RGB latent at $x_0$ with the `q_sample` function to compute $x_t$ and the groundtruth vector field $u_t$

**Comment by danier97** [comment]
> Hi ssssholmes, timestep 400 is a setting here for the noise augmentation, which noises the starting image at x0 a bit to enhance overall model performance. To answer you questions specifically:
> 
> * Like regular flow matching and diffusion model training, we randomly sample t during training
> * We always noise the RGB latent at x0 with the `q_sample` function to compute xt and the groundtruth vector field ut

Hi, very nice work and thank you for your answer above. Just following up your second answer above, when you say "we noise $x_0$  with the `q_sample` to compute  $x_t$", do you mean:
1. you augment data by doing `x_0 = q_sample(x_0, t=400)`, then get input to the UNet with $x_t = tx_1 + (1-t)x_0$, OR
2. you get the input of the UNet with `x_t = q_sample(x_0, t)` where t is randomly sampled?

Also, in the paper from Equation (5) of $\mathcal{L}_{FM}$, it seems that the unet input is obtained via Equation (4), but to my understanding of Flow Matching, shouldn't the input to the UNet be samples from Equation (2), i.e. $p_t(x|z)$?

Thank you very much in advance for your help!
